-- Tabela de Usuários (Simplificada conforme pedido)
CREATE TABLE users (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    name TEXT NOT NULL,
    whatsapp TEXT NOT NULL UNIQUE, -- Chave de identificação
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Tabela de Rifas (Sorteios)
CREATE TABLE raffles (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    image_url TEXT NOT NULL,
    price_per_ticket DECIMAL(10, 2) NOT NULL,
    total_numbers INT NOT NULL, -- Ex: 100, 1000
    status TEXT DEFAULT 'active' CHECK (status IN ('active', 'closed', 'cancelled')),
    winner_number INT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Tabela de Cotas (A "alma" do sistema)
-- Status: 'available', 'reserved', 'sold'
CREATE TABLE tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    raffle_id UUID REFERENCES raffles(id) ON DELETE CASCADE,
    ticket_number INT NOT NULL,
    status TEXT DEFAULT 'available' CHECK (status IN ('available', 'reserved', 'sold')),
    user_id UUID REFERENCES users(id), -- Null se available
    reserved_at TIMESTAMPTZ, -- Data da reserva
    expires_at TIMESTAMPTZ,  -- reserved_at + 20 min
    UNIQUE(raffle_id, ticket_number) -- Impede números duplicados na mesma rifa
);

-- Tabela de Transações (AbacatePay)
CREATE TABLE transactions (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES users(id),
    raffle_id UUID REFERENCES raffles(id),
    external_id TEXT, -- ID do AbacatePay
    amount DECIMAL(10, 2),
    status TEXT DEFAULT 'pending', -- pending, paid, failed
    ticket_numbers INT[], -- Array dos números comprados
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Índices para performance
CREATE INDEX idx_tickets_raffle_status ON tickets(raffle_id, status);
CREATE INDEX idx_tickets_expires_at ON tickets(expires_at) WHERE status = 'reserved';

-- CRON JOB (Supabase Extension pg_cron)
-- Executa a cada 1 minuto para liberar reservas vencidas
-- SELECT cron.schedule('*/1 * * * *', $$
--    UPDATE tickets 
--    SET status = 'available', user_id = NULL, reserved_at = NULL, expires_at = NULL 
--    WHERE status = 'reserved' AND expires_at < NOW();
-- $$);
